# -*- coding: utf-8 -*-
"""prog2ml2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzayEG6wrwiEpkr9fRnGJg3MyxWlGddW
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import(
    accuracy_score,
    ConfusionMatrixDisplay,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)

import matplotlib.pyplot as plt

df=pd.read_csv("stud_data.csv")
print(df)

print(df.head())

print(df.info())

print(df.isnull().sum() )

df.fillna(df.mean(numeric_only=True),inplace=True)
print(df)

print(df.isnull().sum())

X=df[["student_id","age","gender","study_hours","attendance","marks","result"]]

Y=df['result']

encoder=LabelEncoder()
Y=encoder.fit_transform(Y)
print(Y)

encoder.fit_transform(Y)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

print("Training samples:",len(X_train))
print("Testing samples:",len(X_test))

model=DecisionTreeClassifier(random_state=42)

df_processed = df.copy()

X = df_processed[["student_id", "age", "study_hours", "attendance", "marks"]]

gender_encoder = LabelEncoder()
X['gender'] = gender_encoder.fit_transform(df_processed['gender'])

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, Y_train)

print("Model retrained successfully!")

model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

print("actual:",Y_test)
print("predicted:",Y_pred)

accuracy=accuracy_score(Y_test,Y_pred)
print("Accuracy:",accuracy)

precision = precision_score(Y_test, Y_pred,zero_division=0)
print("Precision:", precision)
recall = recall_score(Y_test, Y_pred)
print("Recall:", recall)
f1 = f1_score(Y_test, Y_pred)
print("F1 Score:", f1)

recall = recall_score(Y_test, Y_pred,zero_division=0)
print("Recall:", recall)

f1 = f1_score(Y_test, Y_pred,zero_division=0)
print("F1 Score:", f1)

cm = confusion_matrix(Y_test, Y_pred,labels=encoder.transform(encoder.classes_))
print("Confusion Matrix:")
print(cm)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=encoder.classes_)
disp.plot()
plt.title("Confusion Matrix")
plt.show()

"""### Training and Evaluating a Naive Bayes Classifier"""

from sklearn.naive_bayes import GaussianNB

# Initialize the Naive Bayes model
nb_model = GaussianNB()

# Train the model
nb_model.fit(X_train, Y_train)

print("Naive Bayes model trained successfully!")

# Make predictions on the test set
Y_pred_nb = nb_model.predict(X_test)

print("Naive Bayes predictions:")
print("Actual:", Y_test)
print("Predicted:", Y_pred_nb)

"""#### Naive Bayes Model Evaluation"""

# Calculate evaluation metrics for Naive Bayes
accuracy_nb = accuracy_score(Y_test, Y_pred_nb)
precision_nb = precision_score(Y_test, Y_pred_nb, zero_division=0)
recall_nb = recall_score(Y_test, Y_pred_nb, zero_division=0)
f1_nb = f1_score(Y_test, Y_pred_nb, zero_division=0)

print(f"Naive Bayes Accuracy: {accuracy_nb:.4f}")
print(f"Naive Bayes Precision: {precision_nb:.4f}")
print(f"Naive Bayes Recall: {recall_nb:.4f}")
print(f"Naive Bayes F1 Score: {f1_nb:.4f}")

# Generate Confusion Matrix for Naive Bayes
cm_nb = confusion_matrix(Y_test, Y_pred_nb, labels=encoder.transform(encoder.classes_))
disp_nb = ConfusionMatrixDisplay(confusion_matrix=cm_nb, display_labels=encoder.classes_)

print("Naive Bayes Confusion Matrix:")
print(cm_nb)

disp_nb.plot()
plt.title("Naive Bayes Confusion Matrix")
plt.show()
